### PR TITLE
Test refactor

### PR DESCRIPTION
**Pull request by willrogers**
@GeorgeSheppard a bigger refactor.

### CODE REVIEW

**Review by GeorgeSheppard — APPROVED** [review]

**Comment by willrogers** [comment]
I reduced the log level for the unsubscribe message.

**Comment by willrogers** [comment]
And used the logging levels to suppress some of the noisy tests - I think this is what you had in mind.

**Comment by GeorgeSheppard** [comment]
That's exactly what I had in mind, just checked it out it's much easier to see problems. I do get a fail on coniql.test.ts though, which is confusing as the checks have passed. Do you have any ideas why?

**Comment by willrogers** [comment]
No, everything is passing for me. Can you paste the failure in here?

**Comment by GeorgeSheppard** [comment]
Weird, just switched branches and back again, and it is running fine. If it happens again will be sure to paste it in, should have done it before really so my bad.

**Pull request merged**
