### PR TITLE
Drop down

### PR DESCRIPTION
**Pull request by TimGuiteDiamond**
Added a drop down/card component :+1: 

Comments welcome :smiley:

### CODE REVIEW

**Comment by willrogers** [comment]
This is a nice little widget. My main question is: what happens when you put it in an absolute layout?

**Comment by TimGuiteDiamond** [comment]
> This is a nice little widget. My main question is: what happens when you put it in an absolute layout?

Not sure. Will test today.

**Comment by TimGuiteDiamond** [comment]
You can control the width but not the height. See the below screenshot highlighting the parent div, whose size is set from the JSON, but is significantly less tall than the child div inside it:

image

I suppose this would be alright!? With a recommendation that this widget be primarily used within a relative layout or wrapped in a specific display which controls its overflow?

**Comment by willrogers** [comment]
You can set `min-height` on the `<details>` element. Then if you want it to take up a certain amount of space vertically then it will do, although it won't shrink beyond the contents of the summary.

The font needs to be applied to the `<summary>` element rather than the `<details>` element.

But generally I think this is a nice widget and works well.

**Pull request merged**
