### PR TITLE
Layout & Routing

### PR DESCRIPTION
**Pull request by skyfrench**
Playing around with layouts and nested routing ...

(not proposing we merge this yet, opening request just for illustrative demo purposes).

#75 & #96

### CODE REVIEW

**Comment by skyfrench** [comment]
@TimGuiteDiamond why is props.history undefined in ActionButtonWidget? 
(Simple Example -> DCM Button)

I'd like to pass the RouteComponentProps available and defined and usable in e.g. dynamicPage.tsx through to the widgets to pass into executeActions so that an action can use the browser router manually to open a route (manual equivalent of clicking 'Link'). But given how convoluted that sounds ... maybe I shouldn't be trying to do this?

**Comment by skyfrench** [comment]
Couple of notes:
- Simplified App using #106.
-- but with modification: I have replaced 'name' with 'routePath' to allow completely arbitrary paths to be routed to a page
- There's now a:
-- top level json file (a 'synoptic') loaded by default in a div in App.tsx
-- second div which loads a json file which defines the page layout and possible route locations (e.g. left, right)
- Adding an action of type 'OPEN_PAGE' can be used to load any json page in any location with any macros, e.g. Component 1 (2) has an action to load 'ionpExample' in the 'left' location with a device macro for SR03A-VA-IONP-01 (SR04A-VA-IONP-01). The ionpExample now has a button with an action to open a further device screen in the 'right' location.

**Comment by TimGuiteDiamond** [comment]
@skyfrench why does the ActionButton require a PV? Not all of the actions need them

**Comment by skyfrench** [comment]
> @skyfrench why does the ActionButton require a PV? Not all of the actions need them

Good point - I don't think it necessarily does ...

**Comment by TimGuiteDiamond** [comment]
It does take one in CS-Studio but not sure why :man_shrugging:

**Comment by skyfrench** [comment]
> It does take one in CS-Studio but not sure why 🤷‍♂

It may be assumed all buttons have a status PV?

**Comment by TimGuiteDiamond** [comment]
This has been taken forwards in #128 so perhaps could be closed here?

**Pull request closed without merging**
