### PR TITLE
Logging -- Standardize log levels and document usage

### PR DESCRIPTION
**Pull request by talwrii**
I have found the debug log level particularly useful.

### CODE REVIEW

**Comment by willrogers** [comment]
We don't want `trace` by default do we?

**Comment by willrogers** [comment]
Also I expect there's room for using the `warn` level.

**Comment by willrogers** [comment]
Too late I added a commit and merged.

**Comment by talwrii** [comment]
> We don't want trace by default do we?

Fixed

> Also I expect there's room for using the warn level.

Sure.  Can you think of anything to warn about : )?

I graded the warning into levels... and only really needed four levels. I could imagine using warn for "important info". We might have components be quite chatty about internal state changes on info mode, but only show the importation messages in info mode. But then... if we are showing detailed information from different components we might want to be able to tweak logging per component. 

----

Mutter in general about use cases for logging:

i. Isolating observered behaviour to a particular component: info
ii. Checking what messages to the redux stream look like: debug I was using this to check that process variable names were correct. I imagine it might be useful to filter this
iii. Checking what messages from the network look like
iv. Adding manual console.log lines to a component and checking that they do the correct thing after a particular message.

**Pull request closed without merging**
