### PR TITLE
WIP: Devices

### PR DESCRIPTION
**Pull request by skyfrench**
WIP towards https://github.com/dls-controls/cs-web-proto/issues/174.

### CODE REVIEW

**Comment by willrogers** [comment]
I have seen this - I'll try to take a look soon.

**Comment by willrogers** [comment]
Hi Sky,

This goes all the way round the Redux loop. I think this is the trickiest bit of the code, perhaps with another use case we can work towards cleaning it up a bit.

How are you testing this? I can't find 'Xspress3' in the Coniql code, perhaps you have a dev branch or some yaml files.

Cheers,
Will

**Comment by skyfrench** [comment]
There's a Device Testing link on the menu ...

**Comment by willrogers** [comment]
Does it not ask Coniql for a device over graphql?

I don't think my version of Coniql has any devices.

**Comment by willrogers** [comment]
Or is it coming from the cs-web-proto simulator?

**Comment by skyfrench** [comment]
Yeah I just realised my reply wasn't useful!
I ran the example here - https://coniql.readthedocs.io/en/latest/#devices

**Comment by willrogers** [comment]
Thanks, I have got it working.

**Comment by willrogers** [comment]
This was updated by George Sheppard and has now been merged.

**Pull request closed without merging**
