### PR TITLE
Ensure widgets re-render only if the right PV has changed.

### PR DESCRIPTION
**Pull request by willrogers**
@TimGuiteDiamond I believe this will catch the multiple render problem.

There's some refactoring to do here, but I'd like you to check that it does indeed fix the problem.

### CODE REVIEW

**Comment by TimGuiteDiamond** [comment]
@willrogers have added some tests, as noted here and in #94 the by value tests do not actually appear to be necessary as the same object must be being used to represent this. I would like to add some further tests however related to changing minor elements of objects, such as alarm values and display ranges. Perhaps these will be forced to create entirely new objects which would therefore fail the shallow test.

I think the code should probably be cleaned up a bit, we might add or remove information from pvState arrays in the future, and perhaps a comment explaining why this works with respect to redux?

**Comment by willrogers** [comment]
I refactored a bit. It's worth checking that the actual bug is still fixed!

**Comment by willrogers** [comment]
Looks ok to me.

**Comment by TimGuiteDiamond** [comment]
MultipleWidgetsOneRender
MultipleWidgetsOneRenderDevTools

Merged this into #98 and the above pictures show that indeed only the widgets which is subscribed to a PV value that **changes** is updated, the other two remain idel. Shown above with React profiler and Chrome devTools.

@willrogers this is ready to merge.

I will use this as a base to perform more testing with respect to an increased number of widgets on the screen.

**Pull request merged**
