### PR TITLE
Vtypes

### PR DESCRIPTION
**Pull request by willrogers**
Fairly innocuous but will cause a few conflicts @skyfrench @TimGuiteDiamond

### CODE REVIEW

**Comment by TimGuiteDiamond** [comment]
Why is string separated from VTypes or will this be done the the other types as well?

**Comment by willrogers** [comment]
Probably, yes.

**Comment by TimGuiteDiamond** [comment]
What is the benefit of that over having all the VTypes in one file?

**Comment by willrogers** [comment]
It's going to be a very big file.

**Pull request merged**
