### PR TITLE
Prop types

### PR DESCRIPTION
**Pull request by TimGuiteDiamond**
Only a basic demo so far but demonstrates using prop-types to perform runtime type checking.

Might suggest taking https://github.com/ratehub/check-prop-types and converting to TS and including directly in our project, perhaps this would be more trouble than it is worth? Provides an actual functional interface to prop type checking.

### CODE REVIEW

**Comment by TimGuiteDiamond** [comment]
Merged with latest changes from #76 

Showing build errors due to the checking of PropTypes in a foreign file when TS can't be assured that this attribute will exist. Fair enough but if we were to implement this the error could be disabled for this line.

Also because I am throwing an object as an error, perhaps there is a more graceful way to extract this information, particular to the widget and file but could be hidden within recursive calls?

**Comment by TimGuiteDiamond** [comment]
Actually caught some errors in #76 FrontPage.json and would have helped @skyfrench (and other developers) when developing #92

**Comment by TimGuiteDiamond** [comment]
See #69 for more information

**Comment by willrogers** [comment]
The commit I pushed removes `null` from the inferred proptypes, which simplifies the code again.

I also added some ideas regarding reducing the verbosity of the proptypes code (i.e. type aliases), but they're no big deal either way.

**Comment by TimGuiteDiamond** [comment]
A lot of the extra lines come from the verbosity forced by PropTypes, however as mentioned this is catching errors even with us so is probably worth keeping in for the time being.

**Pull request merged**
